#!/bin/bash

HIERA_VERSIONS="1.3.4 3.3.1 3.4.2"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
cd "$DIR"
EXITCODE=0

for v in $HIERA_VERSIONS; do
  echo "========================================="
  echo "Testing with hiera ${v}"
  echo "========================================="

  set -e
  rm -rf "${DIR}/.bundle"
  rm -f "$DIR/Gemfile.lock"
  set +e

  export HIERA_VERSION="$v"
  if bundle install --path vendor/bundle --clean > "$DIR/bootstrap.out"; then
    rm -f "$DIR/bootstrap.out"
  else
    echo "Failed to install gems for ${v}"
    cat "$DIR/bootstrap.out"
    exit 1
  fi

  if bundle exec rake; then
    :
  else
    EXITCODE=1
  fi
done

exit $EXITCODE
